### ISSUE TITLE
模拟器没跑起来

### ISSUE THREAD

**Issue by sysprint** [rabbitmouse/ZQSearchController#3]
这是报错

Showing Recent Messages
:-1: Multiple commands produce '/Users/sy_sprint/Library/Developer/Xcode/DerivedData/ZQSearchController-esmmuwaxuxoyktdeohrlueaxckmr/Build/Products/Debug-iphonesimulator/ZQSearchController.app/Info.plist':
1) Target 'ZQSearchController' (project 'ZQSearchController') has copy command from '/Users/sy_sprint/Downloads/ZQSearchController-master/Example/Info.plist' to '/Users/sy_sprint/Library/Developer/Xcode/DerivedData/ZQSearchController-esmmuwaxuxoyktdeohrlueaxckmr/Build/Products/Debug-iphonesimulator/ZQSearchController.app/Info.plist'
2) Target 'ZQSearchController' (project 'ZQSearchController') has process command with output '/Users/sy_sprint/Library/Developer/Xcode/DerivedData/ZQSearchController-esmmuwaxuxoyktdeohrlueaxckmr/Build/Products/Debug-iphonesimulator/ZQSearchController.app/Info.plist'

**Comment by rabbitmouse** [comment]
Xcode10更新后的问题 参考https://www.jianshu.com/p/8a8444acdca5

**Comment by sysprint** [comment]
> Xcode10更新后的问题 参考https://www.jianshu.com/p/8a8444acdca5

更新新的版本可以了。  现在有个问题是我想让这个模糊搜索列表的cell上  只显示标题  不需要图片和描述  http://thyrsi.com/t6/395/1540451893x-1404795696.png     请问  我在哪个类里面修改
