### ISSUE TITLE
sdk不能兼容5.7.3版本的sdwebimage，希望有空能解决一下

### ISSUE THREAD

**Issue by MrJoexx** [rabbitmouse/ZQSearchController#6]

**Comment by rabbitmouse** [comment]
具体哪个方法不兼容呢 截个图吧

**Comment by MrJoexx** [comment]
cocoapods 安装sdk只能指定sdwebimage为4.0版本  如果不指定版本就会报错  说zqsearch库不兼容

**Comment by rabbitmouse** [comment]
发布了0.1.9的版本 sd版本大于4.0.0即可 try  pod repo update  && pod update

**Comment by MrJoexx** [comment]
ok  三克油
